source 'https://rubygems.org'

gem 'xcodeproj'
gem 'rest-client'

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
